server:
  port: 8999
spring:
  application:
    name: xhlj-service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # 网关路由配置
        - id: service-common # 路由 id,自定义，只要唯一即可
          uri: lb://service-common #负载均衡
          predicates:
            - Path=/service/common/** #选择路径 以/chat/..开头，路径断言#
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/service/user/**
        - id: service-manager
          uri: lb://service-manager
          predicates:
            - Path=/service/manager/**
        - id: service-active
          uri: lb://service-active
          predicates:
            - Path=/service/active/**
        - id: service-exhibit
          uri: lb://service-exhibit
          predicates:
            - Path=/service/exhibit/**

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
