server:
  port: 8503
spring:
  application:
    name: service-manager
  cloud:
    nacos:
      discovery:
        server-addr: 111.231.60.148:10003
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.231.60.148:10000/xhlj?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 1234
  data:
    redis:
      host: 111.231.60.148
      port: 10001
      password: 123456
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

xhlj:
  live:
    appId: 99dae5bc161d42e2892667677ecb5957
    appCertificate: b7a616507942466d99686432743d8d76
    tokenExpirationInSeconds: 3600
    privilegeExpirationInSeconds: 3600
    key: b2727d05ea6d4795b9e907bfc92d6976
    secret: ec55c90794bb40569765a19176b7cff1
  tencent:
    live:
      pushDomain: push.westlaker.xyz
      pullDomain: pull.westlaker.xyz
      appName: xhlj
      key: d69017a2db9307a1c960a7dde05dab98
    yun:
      secretId: AKIDyujOsCK99CP0WvENNA9CKVVJuLackjZI
      secretKey: jIhR70rqogJjEgEh1CCJUbdq7WwJX1So