server:
  port: 8505

spring:
  application:
    name: service-exhibit
  cloud:
    nacos:
      discovery:
        server-addr: 111.231.60.148:10003
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.231.60.148:10000/xhlj?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 1234
  data:
    redis:
      host: 111.231.60.148
      port: 10001
      password: 123456

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml