server:
  port: 8500

spring:
  application:
    name: service-common
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

xhlj:
  chat:
    apiKey: SMcQAdGStVsfZ1iGrbDbjGjw
    secretKey: kiD7bsUbMZdF6BdvZGBDHgYsszGCZz3r
  minio:
    endpointUrl: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: xhlj