server:
  port: 8500

spring:
  application:
    name: service-common
  cloud:
    nacos:
      discovery:
        server-addr: 111.231.60.148:10003
  data:
    redis:
      host: 111.231.60.148
      port: 10001
      password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

xhlj:
  chat:
    apiKey: SMcQAdGStVsfZ1iGrbDbjGjw
    secretKey: kiD7bsUbMZdF6BdvZGBDHgYsszGCZz3r
  minio:
    endpointUrl: http://111.231.60.148:10002
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: xhlj